INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (1,  1,  null, 'Mr. Dursley stuck his head out of the window.  Suddenly the owl grabbed him by his mop of hair and lifted him into the sky!');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (1,  2,  null, 'Harry Potter then came and magicked really good. The End.');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  2,  null, 'it was the age of wisdom, it was the age of foolishness,');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  2,  4, 'actually it was just the best of times.');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  3,  4, 'it was the epoch of belief, it was the epoch of incredulity, ');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  1,  5, 'it was the season of Light, it was the season of Darkness, ');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  4,  6, 'it was the spring of hope, it was the winter of despair, ');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  1,  7, 'we had everything before us, we had nothing before us, ');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  2,  8, 'we were all going direct to Heaven, we were all going direct the other way—in short, ');
INSERT INTO twists (story_id, author_id, parent_id, bodytext, accepted) VALUES (2,  3,  9, 'the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only.');
