DROP TABLE IF EXISTS votes CASCADE;

CREATE TABLE votes (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  twist_id INTEGER REFERENCES twists(id) ON DELETE CASCADE
);
